const fs = require('fs');

const arDict = {
  "explore.title": "استكشف مصر",
  "explore.subtitle": "من عجائب الماضي إلى الواحات الخفية",
  "explore.map": "خريطة تفاعلية",
  "explore.catAll": "الكل",
  "explore.catAncient": "تاريخي",
  "explore.catMuseum": "متاحف",
  "explore.catNature": "طبيعة",
  "explore.catBeach": "شواطئ",
  "explore.catHidden": "خفية",
  "explore.noRating": "التقييم غير متوفر",
  "explore.noCrowd": "بيانات الازدحام غير متوفرة",
  "explore.exploreDest": "استكشف الوجهة",
  "hidden.title": "مصر الخفية",
  "hidden.subtitle": "اكتشف القصص غير المروية",
  "hidden.mission": "مهمة التأثير الوطني",
  "hidden.missionDesc": "من خلال استكشاف هذه الجواهر الخفية الموثقة، فإنك تساعد بنشاط في توزيع السياحة في جميع أنحاء مصر، وحماية مواقعنا التراثية الكبرى من الازدحام.",
  "hidden.reducedCrowding": "تقليل الازدحام",
  "hidden.loading": "جاري تحميل الجواهر الخفية...",
  "hidden.noData": "بيانات زيارة المنصة غير متوفرة",
  "hidden.aiRec": "توصية الذكاء الاصطناعي",
  "hidden.noAi": "رؤية الذكاء الاصطناعي غير متوفرة",
  "passport.title": "جواز السفر السياحي",
  "passport.journey": "رحلتك السياحية",
  "passport.totalStamps": "إجمالي الأختام",
  "passport.status": "الحالة: موثق",
  "passport.visited": "الأماكن المزارة",
  "passport.achievements": "الإنجازات والشارات",
  "passport.start": "ابدأ الاستكشاف لجمع أول ختم لك",
  "passport.planned": "رحلاتي المخطط لها",
  "emergency.title": "مساعد الطوارئ",
  "emergency.hospital": "ابحث عن أقرب مستشفى",
  "emergency.police": "ابحث عن أقرب مركز شرطة",
  "emergency.disclaimer": "مصر إكس لا تحل محل خدمات الطوارئ الرسمية",
  "kids.title": "وضع الأطفال",
  "kids.subtitle": "تعرف على مصر القديمة من خلال الألعاب والحقائق الممتعة",
  "kids.start": "ابدأ المغامرة",
  "kids.games": "العب الألعاب",
  "memories.title": "ذكرياتي في مصر",
  "memories.add": "أضف ذكرى",
  "memories.story": "قصتك في مصر تبدأ هنا",
  "memories.upload": "رفع صورة",
  "memories.select": "اختر المكان",
  "memories.caption": "الوصف",
  "expenses.title": "مصاريف الرحلة",
  "expenses.add": "أضف مصروف",
  "expenses.noExpenses": "لم يتم تسجيل أي مصاريف بعد",
  "aiGuide.title": "دليل الرؤية بالذكاء الاصطناعي",
  "aiGuide.snap": "التقط صورة لأي معلم...",
  "aiGuide.identify": "تعرف بالذكاء الاصطناعي",
  "aiGuide.high": "ثقة عالية",
  "aiGuide.med": "ثقة متوسطة",
  "aiGuide.low": "ثقة منخفضة",
  "aiGuide.desc": "وصف عام من الذكاء الاصطناعي",
  "aiGuide.verified": "موقع موثق",
  "aiGuide.viewFull": "عرض التفاصيل الكاملة",
  "news.title": "أخبار السياحة في مصر",
  "news.learnMore": "اعرف المزيد",
  "news.source": "المصدر:",
  "login.subtitle": "النظام البيئي الوطني للسياحة الذكية",
  "login.signIn": "تسجيل الدخول / إنشاء حساب",
  "login.access": "ادخل إلى جواز سفرك ورحلاتك ودليلك الذكي.",
  "login.demoTourist": "تسجيل الدخول كسائح تجريبي",
  "login.demoBusiness": "تسجيل الدخول كنشاط تجاري تجريبي",
  "login.govLogin": "تسجيل الدخول الحكومي",
  "planner.title": "خطط لرحلتك في مصر",
  "planner.prompt": "أخبرنا عن رحلة أحلامك...",
  "planner.whereFrom": "من أين أنت؟",
  "planner.duration": "مدة الرحلة",
  "planner.budget": "الميزانية",
  "planner.interests": "ما هي اهتماماتك؟",
  "planner.intAncient": "مصر القديمة",
  "planner.intBeaches": "شواطئ",
  "planner.intAdventure": "مغامرة",
  "planner.intFood": "طعام",
  "planner.intCulture": "ثقافة",
  "planner.intNature": "طبيعة",
  "planner.styleSolo": "فردي",
  "planner.styleCouple": "زوجان",
  "planner.styleFamily": "عائلة",
  "planner.styleGroup": "مجموعة",
  "planner.paceRelaxed": "مريح",
  "planner.paceBalanced": "متوازن",
  "planner.pacePacked": "مكثف",
  "planner.generateBtn": "إنشاء رحلتي في مصر",
  "planner.itineraryTitle": "مسار رحلتك المخصص",
  "planner.modifyBtn": "تعديل الخطة",
  "nav.brand": "مصر إكس",
  "destinations.featured": "وجهات مميزة",
  "destinations.subtitle": "من عجائب الماضي إلى الواحات الخفية",
};

const frDict = {
  "explore.title": "Explorer l'Égypte",
  "explore.subtitle": "Des merveilles antiques aux oasis cachées",
  "explore.map": "Carte Interactive",
  "explore.catAll": "Tout",
  "explore.catAncient": "Antique",
  "explore.catMuseum": "Musées",
  "explore.catNature": "Nature",
  "explore.catBeach": "Plages",
  "explore.catHidden": "Caché",
  "explore.noRating": "Évaluation non disponible",
  "explore.noCrowd": "Données d'affluence non disponibles",
  "explore.exploreDest": "Explorer la Destination",
  "hidden.title": "L'Égypte Cachée",
  "hidden.subtitle": "Découvrez les histoires inédites",
  "hidden.mission": "Mission d'Impact National",
  "hidden.missionDesc": "En explorant ces joyaux cachés vérifiés, vous aidez activement à répartir le tourisme à travers l'Égypte, protégeant nos sites patrimoniaux majeurs de la surpopulation.",
  "hidden.reducedCrowding": "Moins de Foule",
  "hidden.loading": "Chargement des joyaux cachés...",
  "hidden.noData": "Données de visite non disponibles",
  "hidden.aiRec": "Recommandation de l'IA",
  "hidden.noAi": "Aperçu de l'IA non disponible",
  "passport.title": "Passeport Touristique",
  "passport.journey": "Votre Parcours",
  "passport.totalStamps": "Total des Tampons",
  "passport.status": "Statut : Vérifié",
  "passport.visited": "Lieux Visités",
  "passport.achievements": "Réalisations et Badges",
  "passport.start": "Commencez à explorer pour collecter votre premier tampon",
  "passport.planned": "Mes Voyages Prévus",
  "emergency.title": "Assistant d'Urgence",
  "emergency.hospital": "Trouver l'Hôpital le Plus Proche",
  "emergency.police": "Trouver le Commissariat le Plus Proche",
  "emergency.disclaimer": "EgyptX AI ne remplace pas les services d'urgence officiels",
  "kids.title": "Mode Enfants",
  "kids.subtitle": "Découvrez l'Égypte antique à travers des jeux et des faits amusants",
  "kids.start": "Commencer l'Aventure",
  "kids.games": "Jouer aux Jeux",
  "memories.title": "Mes Souvenirs d'Égypte",
  "memories.add": "Ajouter un Souvenir",
  "memories.story": "Votre histoire égyptienne commence ici",
  "memories.upload": "Télécharger une Photo",
  "memories.select": "Sélectionner un Lieu",
  "memories.caption": "Légende",
  "expenses.title": "Dépenses du Voyage",
  "expenses.add": "Ajouter une Dépense",
  "expenses.noExpenses": "Aucune dépense enregistrée pour le moment",
  "aiGuide.title": "Guide de Vision IA",
  "aiGuide.snap": "Prenez une photo de n'importe quel monument...",
  "aiGuide.identify": "Identifier avec l'IA",
  "aiGuide.high": "CONFIANCE ÉLEVÉE",
  "aiGuide.med": "CONFIANCE MOYENNE",
  "aiGuide.low": "CONFIANCE FAIBLE",
  "aiGuide.desc": "Description Générale de l'IA",
  "aiGuide.verified": "Lieu Vérifié",
  "aiGuide.viewFull": "Voir les Détails Complets",
  "news.title": "Actualités du Tourisme en Égypte",
  "news.learnMore": "En Savoir Plus",
  "news.source": "Source :",
  "login.subtitle": "L'Écosystème National du Tourisme Intelligent",
  "login.signIn": "Se Connecter / S'inscrire",
  "login.access": "Accédez à votre passeport, vos voyages et votre guide intelligent.",
  "login.demoTourist": "Connexion en tant que Touriste Démo",
  "login.demoBusiness": "Connexion en tant qu'Entreprise Démo",
  "login.govLogin": "Connexion Gouvernementale",
  "planner.title": "Planifiez Votre Voyage en Égypte",
  "planner.prompt": "Parlez-nous de votre voyage de rêve...",
  "planner.whereFrom": "D'où venez-vous ?",
  "planner.duration": "Durée du Voyage",
  "planner.budget": "Budget",
  "planner.interests": "Qu'est-ce qui vous intéresse ?",
  "planner.intAncient": "Égypte Antique",
  "planner.intBeaches": "Plages",
  "planner.intAdventure": "Aventure",
  "planner.intFood": "Nourriture",
  "planner.intCulture": "Culture",
  "planner.intNature": "Nature",
  "planner.styleSolo": "Solo",
  "planner.styleCouple": "Couple",
  "planner.styleFamily": "Famille",
  "planner.styleGroup": "Groupe",
  "planner.paceRelaxed": "Détendu",
  "planner.paceBalanced": "Équilibré",
  "planner.pacePacked": "Intense",
  "planner.generateBtn": "Générer Mon Voyage en Égypte",
  "planner.itineraryTitle": "Votre Itinéraire Personnalisé",
  "planner.modifyBtn": "Modifier le Plan",
  "nav.brand": "EgyptX AI",
  "destinations.featured": "Destinations Phares",
  "destinations.subtitle": "Des merveilles antiques aux oasis cachées",
};

function updateLang(lang, dict) {
  const file = "messages/" + lang + ".json";
  let data = JSON.parse(fs.readFileSync(file, 'utf8'));
  for (const [key, val] of Object.entries(dict)) {
    const parts = key.split('.');
    let cur = data;
    for (let i = 0; i < parts.length - 1; i++) {
      cur[parts[i]] = cur[parts[i]] || {};
      cur = cur[parts[i]];
    }
    cur[parts[parts.length - 1]] = val;
  }
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
}

updateLang('ar', arDict);
updateLang('fr', frDict);
console.log('Updated Arabic and French JSONs with proper translations.');
